Description: EC2 & ASG setup for FTP server

Parameters:
  # inject in the latest AMI
  Linux2Ami:
    Type: String
  # used to open up ssh port
  myIpAddress:
    Type: String
  UserDataScript:
    Type: String
  spotInstancePrice:
    Type: String
    Default: "0.015"
  stackName:
    Type: String
  instanceType:
    Type: String
    Default: t3.medium
  AvailabilityZone:
    Type: String
  VpcId:
    Type: String

Resources:

  # Template that will be used by the ASG to create EC2 instances
  FtpLauchConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      # IamInstanceProfile: !Ref CsServerInstanceProfile
      ImageId: !Sub ${Linux2Ami}
      InstanceMonitoring: false # When detailed monitoring is enabled, CloudWatch generates metrics every minute and you're charged a fee. 
      InstanceType: !Sub ${instanceType} 
      AssociatePublicIpAddress: true
      SpotPrice: !Sub "${spotInstancePrice}"
      SecurityGroups: 
        - !Ref FtpSecurityGroup
      UserData:
        Fn::Base64: !Ref UserDataScript

  FtpSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for FTP server
      GroupName: ftp-server-sg
      SecurityGroupIngress:
        - Description: SSH from my current ip
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${myIpAddress}"
        - Description: Web from my current ip for testing FTP
          IpProtocol: tcp
          FromPort: 21
          ToPort: 21
          CidrIp: !Sub "${myIpAddress}"
      VpcId:
        !Ref VpcId
        # Fn::ImportValue: !Sub "${stackName}-vpc"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sg"

  # toggle the min and max size to have instances deployed
  FtpServerAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: 
        - !Ref AvailabilityZone
        # - eu-west-1a
      HealthCheckGracePeriod: 10 # in seconds
      HealthCheckType: EC2
      LaunchConfigurationName: !Ref FtpLauchConfig
      MaxSize: "1"
      MinSize: "1"
      TerminationPolicies: 
        - OldestInstance
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ASG"
          PropagateAtLaunch: true
      VPCZoneIdentifier:
        - subnet-07b32998cce87442a
        # - Fn::ImportValue: !Sub "${stackName}-net-pub-subnet-a" 

# Exporting outputs to use in downstream stacks
Outputs:
  StackName:
    Value: !Ref AWS::StackName
